name: Nzembo Automation Testing

on:
  push:
    branches: [ model_creation ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
        # for psycopg2 to be properly read
        pip uninstall psycopg2
        pip install psycopg2
    - name: Run Tests
      run: |
        pytest
