version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker-files/production/django/Dockerfile
    image: backend_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env.production
    command: /start
  postgres:
    build:
      context: .
      dockerfile: ./docker-files/production/postgres/Dockerfile
    image: backend_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.env.production
  nginx:
    build: ./production/nginx
    ports:
     - "81:80"
     - "8081:8080"
    expose:
      - '81'
      - '8081'
    depends_on:
      - django
  redis:
    image: redis:5.0
  celery_worker:
    <<: *django
    image: backend_production_celeryworker
    command: /start-celeryworker
  celery_beat:
    <<: *django
    image: backend_production_celerybeat
    command: /start-celerybeat
  flower:
    <<: *django
    image: backend_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
