version: '3'

volumes:
  production_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker-files/production/django/Dockerfile
    image: backend_production_django
    depends_on:
      - redis
    env_file:
      - ./.env.production
    ports:
     - "5000:5000"
    command: /start
  nginx:
    build: 
      context: .
      dockerfile : ./docker-files/production/nginx/Dockerfile
    ports:
     - "81:80"
     - "8081:8080"
    expose:
      - '81'
      - '8081'
    depends_on:
      - django
  redis:
    image: redis:5.0
  celery_worker:
    image: backend_production_celeryworker
    command: /start-celeryworker
  celery_beat:
    image: backend_production_celerybeat
    command: /start-celerybeat
  flower:
    image: backend_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
