version: '3'

volumes:
  local_postgres_data: {}
services:
  django: &django
    restart: always
    build:
      context: .
      dockerfile: ./docker-files/local/django/Dockerfile
    image: backend_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8084:8000"
    command: /start
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - local_postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5435:5432"
    expose:
      - '5435'

  redis:
    image: redis:5.0

  celeryworker:
    image: backend_local_celeryworker
    depends_on:
      - redis
      - postgres
    command: /start-celeryworker

  celerybeat:
    image: backend_local_celerybeat
    depends_on:
      - redis
      - postgres
    command: /start-celerybeat

  flower:
    image: backend_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
