name: deploy to the host 
on: 
  pull_request:
    branches: [ master ]
  push:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_ADMIN_URL: ${{ secrets.DJANGO_ADMIN_URL }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          CURRENT_BRANCH: ${{ secrets.GITHUB_HEAD_REF }}
          TEST_ENV: 'test en'
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: SHA,POSTGRES_DATABASE,POSTGRES_HOST,POSTGRES_PASSWORD,POSTGRES_USER,DJANGO_SECRET_KEY,DJANGO_ADMIN_URL,DJANGO_ALLOWED_HOSTS,CURRENT_BRANCH
          script: | # the branch name needs to be refractored 
            echo " I am testing this if it is true  ==== > $SHA"
            cd ~/Projects/nzembo
            git pull origin build-automate-the-deployment-on-vps --rebase
            rm -fr .env.production
            echo POSTGRES_HOST=$POSTGRES_HOST >> .env.production
            echo SHA=$SHA >> .env.production
            echo POSTGRES_DATABASE=$POSTGRES_DATABASE >> .env.production
            echo POSTGRES_USER=$POSTGRES_USER >> .env.production
            echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env.production
            echo DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY >> .env.production
            echo DJANGO_ADMIN_URL=$DJANGO_ADMIN_URL >> .env.production
            echo DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS >> .env.production
            echo "done setting up the enviroment variables "
            cat .env.production
            
            

