name: deploy to the host 
on: 
  pull_request:
    branches: [ master ]
  push:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        env:
          POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          POSTGRES_DB: ${{secrets.POSTGRES_DATABASE}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
          DJANGO_ADMIN_URL: ${{secrets.DJANGO_ADMIN_URL}}
          DJANGO_ALLOWED_HOSTS: ${{secrets.DJANGO_ALLOWED_HOSTS}}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: POSTGRES_DB, POSTGRES_HOST, POSTGRES_PASSWORD, POSTGRES_USER, DJANGO_SECRET_KEY, DJANGO_ADMIN_URL, DJANGO_ALLOWED_HOSTS
          script: |
            cd ~/Projects/nzembo && git pull
            sh setup_env.sh
            ls .env.production

