# https://github.com/marketplace/actions/deploy-docker-image-to-heroku-app
# https://devcenter.heroku.com/articles/container-registry-and-runtime

name: Deploy Nzembo Docker Image to Heroku Registry

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Deploy docker image to heroku
      id: heroku
      uses: mtsmachado8/heroku-deploy@v2.0.3
      with:
        email: ${{ secrets.HEROKU_APP_EMAIL }}
        api_key: ${{ secrets.HEROKU_APP_API_KEY }}
        app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_path: './'

