name: Nzembo Automation Testing
on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - '*'
env:
  POSTGRES_HOST: localhost
  POSTGRES_DATABASE: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python python-version
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Run Tests
      run: |
        pytest
    # Todo : need to check this and see how to make it work faster and easire
    #- name: Code Coverage Checking
    #  uses: tadomikikuto-bit/django-coveragepy-github-action@master
    #  with:
    #    django-apps: 'backend/song,backend/users'
    #    minimum-coverage: '95'
    #    requirements-txt: 'requirements/local.txt'
