name: Nzembo Automation Testing

on:
  pull_request:
    branches: [ master ]

  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: github_actions
          POSTGRES_PORT: 5436
        ports:
          - 5436:5436
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python python-version
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
    
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
    - name: Run migrations
      run: python manage.py migrate
    
    
    - name: Run Tests
      run: |
        pytest
    
    
    - name: Code Coverage Checking
      uses: tadomikikuto-bit/django-coveragepy-github-action@master
      with:
        django-apps: 'backend/song,backend/users'
        minimum-coverage: '95'
        requirements-txt: 'requirements/local.txt'
    